steps:
  - name: 'adoptopenjdk/openjdk11:jdk-11.0.11_9-alpine'
    id: 'build'
    entrypoint: '/workspace/gradlew'
    args: ['--no-daemon', '--console', 'plain', '--info', '--stacktrace', 'check', 'bootJar']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'buildImage'
    waitFor:
      - build
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/product-api-service:${_TAG}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'pushImage'
    args: ['push', 'gcr.io/${PROJECT_ID}/product-api-service:${_TAG}']

  - name: 'alpine:3.7'
    args: ['sed', '-i', 's#@IMAGE_NAME@#gcr.io/${PROJECT_ID}/product-api-service:${_TAG}#g', deployment/k8s/deployment.yaml]

  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'Prepare deploy'
    args:
      - 'prepare'
      - '--filename=deployment/k8s'
      - '--image=gcr.io/${PROJECT_ID}/product-api-service:${_TAG}'
      - '--app=product-api-service'
      - '--version=${_TAG}'
      - '--namespace=api-services'
      - '--output=output'
      - '--annotation=gcb-build-id=$BUILD_ID'
      - '--verbose'

  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'Apply deploy'
    args:
      - 'apply'
      - '--filename=output/expanded'
      - '--namespace=$_K8S_NAMESPACE'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
timeout: 2500s
substitutions:
  _TAG:
  _K8S_NAMESPACE: 'api-services'
  _GKE_CLUSTER:
  _GKE_LOCATION: