apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-service
  labels:
    app: product-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api-service
  template:
    metadata:
      labels:
        app: product-api-service
    spec:
      containers:
        - name: product-api
          image: @IMAGE_NAME@
          ports:
          - containerPort: 80
          readinessProbe:
            path: /health
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m