apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: product-api-service-hpa
  labels:
    app: product-api-service
spec:
  scaleTargetRef:
    kind: Deployment
    name: product-api-service
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80